name: CD - Release Pipeline
on:
  push:
    tags:
      - 'v*' # REQUISITO: Solo corre por tag
jobs:
  release:
    uses: Cristobal1203/AUY1104-CristobalTapia-Main/.github/workflows/deploy-api.yaml@main
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}